### ISSUE TITLE
Petición para añadir Ubuntuleon.com al planet de Colombia

### ISSUE THREAD

**Issue by ferlanero** [planetalinux/planetalinux#242]
Buenos días.

Les escribo para solictar la inclusión de ubuntuleon.com en el Planet de Ubuntu Colombia después de haber estado con ustedes como ponente en la UbuConLA 2014 de Cartagena de Indias.

El feed es de Ubuntu León es:

http://www.ubuntuleon.com/feeds/posts/default

Mis agradecimientos de antemano.

Reciban un cordial saludo!

**Comment by julioh** [comment]
No dieron respuesta.
