### ISSUE TITLE
Solicitud para agregar blog

### ISSUE THREAD

**Issue by rigo** [planetalinux/planetalinux#246]
Estimados administradores de Planeta Linux,

Les solicito de la manera más atenta consideren agregar mi blog personal a Planeta Linux en la instancia correspondiente a México por favor. El URL de la fuente correspondiente es: http://rigobertoc.wordpress.com/feed/ ¿Sería posible incluir un vínculo hacia mi perfil en identi.ca? http://identi.ca/rigocalleja

Mil gracias.

**Comment by julioh** [comment]
Hola! Rigoberto Calleja

Ya te he agregado a la instancia de Planeta Linux que
solicitaste. ¡Bienvenid@!

Te pedimos que esperes un par de horas para que aparezcas
en el sitio.

También, quisiéramos recordarte que Planeta Linux ha crecido
por gente como tú, por la comunidad usuaria de Linux y
software libre en Latinoamérica que quiere ser parte de este
proyecto. Por ello es que le solicitamos a los nuevos integrantes
que por favor escriban un post en su blog invitando a sus
lectores a leer o unirse a Planeta Linux. Es sólo así como,
de boca en boca, nos hemos dado a conocer y hemos ido
creciendo.

No dudes en contactar nos por cualquier eventualidad.

Bienvenido
