### ISSUE TITLE
Solicitud para agregar Systerminal.com

### ISSUE THREAD

**Issue by joseEnrique** [planetalinux/planetalinux#250]
Buenas planeta linux,

nos gustaría enormemente que agregarais systerminal.com a vuestro portal

http://www.systerminal.com/feed/

Gracias.

**Comment by julioh** [comment]
Saludos necesito nombre, correo y a que pais esta interesado en salir

**Comment by joseEnrique** [comment]
Systerminal.com systerminal.com@gmail.com. España
Eso son los datos del sitio. Los mios son Jose Enrique.
Joseenriqueruiznavarro@gmail.com

**Comment by julioh** [comment]
Saludos no agregamos portales, que no son personales. esto es un proyecto que no lleva el nombre tuyo como tal, te indico, planetalinux nace de blog personales, es por ende los datos que pedia anteriormente.
