### ISSUE TITLE
Arquetype ( nueva distribucion de linux )

### ISSUE THREAD

**Issue by arquetype** [planetalinux/planetalinux#254]
Acabamos de publicar una nueva distribucion de linux basada en fedora, con el objetivo de ofrecer al usuario el maximo rendimiento en su pc.

Arquetype tiene una arquetecture de x86_64, aunque se incluyen las principales librerias de 32 bits por si necesitan instalar alguna aplicacion que no soporte 64 bits.

Tengo que destacar, que se ha incluido todo el software que normalmente necesita un usuario ( LibreOffice, vlc, thunderbird, Virtual Machine Manager, flash player......), al igual que un gran numero de herramientas de desarrollo ( compilacion de paquetes, git, mercurial, development tools & libraries, creacion de repositorios......).

Nos gustaria que cuando dispusieran de algun tiempo pudieran probar nuestra distribucion y hacer una valoracion sobre ella.

Links de Arquetype:
http://arquetype.org
http://community.arquetype.org

Links sociales:
https://www.facebook.com/profile.php?id=100008211558840
https://twitter.com/ArquetypeLinux
https://plus.google.com/u/1/communities/112759823460541622182
 

Un saludo, Gonzalo Ponce

**Comment by julioh** [comment]
Saludos Gracias por la informacion.
