### ISSUE TITLE
Solicitud para agregar The Linux Alchemist

### ISSUE THREAD

**Issue by BrunoEV** [planetalinux/planetalinux#255]
Estimados administradores de Planeta Linux, me gustaría agregar mi blog (The Linux Alchemist) al planeta de España. Mis datos son los siguiente:

 - Nombre: The Linux Alchemist
 - Email: bruno (dot) exposito (at) openmailbox (dot) com
 - URL: https://thelinuxalchemist.wordpress.com
 - Feed: https://thelinuxalchemist.wordpress.com/feed
 - País: España

**Comment by julioh** [comment]
Saludos Necesito tu nombre completo.

**Comment by julioh** [comment]
no recibimos respuesta.
