### ISSUE TITLE
Solicitud para agregar Web LiGNUx

### ISSUE THREAD

**Issue by BreoganGal** [planetalinux/planetalinux#256]
Nombre: Asociación LiGNUx
Correo electrónico: social@lignux.com
Url para Gente: http://lignux.com/
Url para Feed: http://lignux.com/feed/
País: España

**Comment by julioh** [comment]
Hola! Asociación LiGNUx

Ya te he agregado a la instancia de Planeta Linux que
solicitaste. ¡Bienvenid@!

Te pedimos que esperes un par de horas para que aparezcas
en el sitio.

También, quisiéramos recordarte que Planeta Linux ha crecido
por gente como tú, por la comunidad usuaria de Linux y
software libre en Latinoamérica que quiere ser parte de este
proyecto. Por ello es que le solicitamos a los nuevos integrantes
que por favor escriban un post en su blog invitando a sus
lectores a leer o unirse a Planeta Linux. Es sólo así como,
de boca en boca, nos hemos dado a conocer y hemos ido
creciendo.

No dudes en contactar nos por cualquier eventualidad.

Bienvenido

**Comment by julioh** [comment]
https://github.com/planetalinux/planetalinux/commit/6bce7d3540cf64fca69ba22d65cb6ecffa14b535
