### ISSUE TITLE
Solicitud agregar al planet NI SalRocks.wordpress.com

### ISSUE THREAD

**Issue by riper81** [planetalinux/planetalinux#257]
Hola me gustaria solicitar que se agregara mi blog a la lista de blogs de Nicaragua.

https://salrocks.wordpress.com

Saludos y gracias de antemano.

**Comment by riper81** [comment]
nombre completo: salvador ernesto aguilar sevilla
correo electrónico: sal.aguilar81@gmail.com 
URL del feed de tu blog: https://salrocks.wordpress.com/feed/
País: nicaragua

**Comment by julioh** [comment]
Hola! Salvador Aguilar 

Ya te he agregado a la instancia de Planeta Linux que
solicitaste. ¡Bienvenid@!

Te pedimos que esperes un par de horas para que aparezcas
en el sitio.

También, quisiéramos recordarte que Planeta Linux ha crecido
por gente como tú, por la comunidad usuaria de Linux y
software libre en Latinoamérica que quiere ser parte de este
proyecto. Por ello es que le solicitamos a los nuevos integrantes
que por favor escriban un post en su blog invitando a sus
lectores a leer o unirse a Planeta Linux. Es sólo así como,
de boca en boca, nos hemos dado a conocer y hemos ido
creciendo.

No dudes en contactar nos por cualquier eventualidad.

Bienvenido
