### ISSUE TITLE
Solicitud de agregar blog

### ISSUE THREAD

**Issue by mariotello** [planetalinux/planetalinux#258]
Nombre: Mario Tello
Nombre Blog: Mario Tello Blog
Correo electrónico: tyo100 at gmail.com
Feed: http://www.mariotello.mx/blog/category/linux/feed/
País: Mexico

**Comment by julioh** [comment]
Hola! Mario Tello

Ya te he agregado a la instancia de Planeta Linux que
solicitaste. ¡Bienvenid@!

Te pedimos que esperes un par de horas para que aparezcas
en el sitio.

También, quisiéramos recordarte que Planeta Linux ha crecido
por gente como tú, por la comunidad usuaria de Linux y
software libre en Latinoamérica que quiere ser parte de este
proyecto. Por ello es que le solicitamos a los nuevos integrantes
que por favor escriban un post en su blog invitando a sus
lectores a leer o unirse a Planeta Linux. Es sólo así como,
de boca en boca, nos hemos dado a conocer y hemos ido
creciendo.

No dudes en contactar nos por cualquier eventualidad.

Bienvenido

**Comment by julioh** [comment]
https://github.com/planetalinux/planetalinux/commit/cb2705643413a5c5d1b8c8c7ef3fe4a53ae9d579
