### ISSUE TITLE
Cambio de URL del RSS

### ISSUE THREAD

**Issue by muammar** [planetalinux/planetalinux#259]
Hola. 

Recientemente he migrado mi sitio a github pages y he tenido que cambiar las URL de los RSS de mi blog. La nueva dirección para posts de planetalinux es:

```
http://muammar.me/blog/category/linux/feed.xml
```

Muchas gracias. 

Saludos,

**Comment by julioh** [comment]
Saludos Muammar

Esta listo el cambio del feed.

https://github.com/planetalinux/planetalinux/commit/55db86f86d5e06fed3d7ccdcf07b18fd963876c7

Sin mas

**Comment by muammar** [comment]
@julioh Muchas gracias por el cambio. Saludos.
