### ISSUE TITLE
Solicitud para eliminar "El Abismo de Tux y agregar The J*"

### ISSUE THREAD

**Issue by tuxtor** [planetalinux/planetalinux#260]
Recientemente he decidido dar de baja mi blog en español:

http://tuxtor.shekalug.org/

Para dar paso a un blog más tecnico en ingles

http://vorozco.com/blog/
https://feeds.feedburner.com/the-j

Ya que el planet solo admite un blog por persona, me gustaria eliminar "El Abismo de Tux" y si fuera posible me gustaria agregar mi nuevo blog a Planeta Linux Guatemala.

**Comment by julioh** [comment]
Saludos Victor

Tu feed fue cambiado, espera los cambios y nos asvisas,

Ticket   728668b
