### ISSUE TITLE
Solicitud Eliminar blog de Clever Flores y agregar Blog de Aula Útil

### ISSUE THREAD

**Issue by cleverflores** [planetalinux/planetalinux#261]
Actualmente dirijo un centro de capacitación en Linux y OpenSource (Aula Útil)
pido que se retire mi blog antiguo de blogspot (cleverflores) y se agregue el blog de Aula Útil http://aulautil.com/blog/ y sus
feeds http://aulautil.com/feed/

**Comment by vicm3** [comment]
Blog y URL inexistente.
