### ISSUE TITLE
Agregar mi sitio al planeta linux

### ISSUE THREAD

**Issue by kuboosoft** [planetalinux/planetalinux#264]
Espero se me sea incluido. Gracias
http://kuboosoft.blogspot.com/

**Comment by julioh** [comment]
Saludos Necesitamos mas información

Nombre autor: 
Nombre del blog:
URL: 
URL feeds posts Linux: 
Descripción del blog: Trata sobre temas relacionados con la administración de sistemas informáticos, en la URL del feed, ya quedan filtrados los posts específicos de temática Linux.

**Comment by julioh** [comment]
Cuando la tengas, abres otro ticket por favor, voy a cerrarlo
