### ISSUE TITLE
Solicitud de mejora: posibilidad de incluir vínculo hacia perfiles de Redes Sociales Federadas

### ISSUE THREAD

**Issue by rigo** [planetalinux/planetalinux#266]
En el sitio web, en el caso de algunos autores, se muestra un vínculo hacia su perfil de Twitter. A través de esta solicitud de mejora, solicito de la manera más atenta, que exista la posibilidad de incluir un vínculo hacia perfiles de Redes Sociales Federadas tales como las que están basadas en Pump.io y GNU social.

Gracias.

**Comment by julioh** [comment]
@damog Que opinas de esto?
