### ISSUE TITLE
Solicitud de mejora: agregar vínculo perfil Twitter Planeta Linux

### ISSUE THREAD

**Issue by rigo** [planetalinux/planetalinux#267]
Estimados,

Por medio de esta solicitud de mejora, sugiero de la manera más atenta, que en el sitio web se incluya un vínculo hacia el perfil de Twitter de Planeta Linux.

Atentamente.

**Comment by julioh** [comment]
Saludos Ya lo tenemos

![p1](https://cloud.githubusercontent.com/assets/87648/11046457/c890aa0c-86ff-11e5-8f8e-33285c02d1c9.png)

Fijate en la imagen como sale la url hacia el twitter.

**Comment by rigo** [comment]
Estimado Julio. Gracias por tu respuesta. Según advierto, el vínculo al que te refieres es hacia el perfil de Twitter del autor en cuestión (en este caso se trata de ti). Sin embargo, yo me refería al perfil de Twitter de Planeta Linux (@planetalinux). Saludos.

**Comment by julioh** [comment]
Saludos Lo tomaremos en cuentos, Gracias por la recomendacion
