### ISSUE TITLE
Solicitud para añadir el blog a Planeta Linux

### ISSUE THREAD

**Issue by SYSADMIT** [planetalinux/planetalinux#268]
Solicitud para añadir el blog a Planeta Linux.

Aquí estan los datos:

Nombre autor: Xavier Genestós
Nombre del blog: SYSADMIT
URL: http://www.sysadmit.com
URL feeds posts Linux: http://www.sysadmit.com/feeds/posts/default/-/Linux
Descripción del blog: Trata sobre temas relacionados con la administración de sistemas informáticos, en la URL del feed, ya quedan filtrados los posts específicos de temática Linux.

**Comment by julioh** [comment]
Saludos dos cosas Xavier

Nos podrias facilitar el correo y tambien en que pais quieres participar

**Comment by SYSADMIT** [comment]
Por supuesto:

- El correo:
https://1.bp.blogspot.com/-wwCVH3radSc/V4qkhP78ucI/AAAAAAAADig/iZeeqZfEt8ggLZZu4dfdc3US9fvrDFc0QCLcB/s1600/mail-SYSADMIT.png

** Te indico el correo electrónico como imagen para evitar el spam.*

- El país: España.

Muchas gracias,

Xavier.

**Comment by julioh** [comment]
Hola! Xavier

Ya te he agregado a la instancia de Planeta Linux que
solicitaste. ¡Bienvenid@!

Te pedimos que esperes un par de horas para que aparezcas
en el sitio.

También, quisiéramos recordarte que Planeta Linux ha crecido
por gente como tú, por la comunidad usuaria de Linux y
software libre en Latinoamérica que quiere ser parte de este
proyecto. Por ello es que le solicitamos a los nuevos integrantes
que por favor escriban un post en su blog invitando a sus
lectores a leer o unirse a Planeta Linux. Es sólo así como,
de boca en boca, nos hemos dado a conocer y hemos ido
creciendo.

No dudes en contactar nos por cualquier eventualidad.

Bienvenido
