### ISSUE TITLE
Solicitud para incluir mi blog a Planeta Linux

### ISSUE THREAD

**Issue by Rogergonzalez21** [planetalinux/planetalinux#269]
Buenas.

Quisiera que se tomara en consideración mi blog personal.

Aquí están los datos:

Nombre autor: Roger González
URL: http://rogerandresgonzalez.com.ve
URL feed de posts de tecnología: http://rogerandresgonzalez.com.ve/feeds/tecnologia.atom.xml
URL feed de posts de Programación en Python: http://rogerandresgonzalez.com.ve/feeds/programacion.atom.xml

Este es mi blog personal, en el que principalmente hablo de Python y tecnología, entre otras cosas mas.

**Comment by julioh** [comment]
Saludos Roger si tienes una url que este arriba hazlo saber en otro ticket.
No funciona
Gracias de antemano
