### ISSUE TITLE
Solicitud para incluir mi blog a Planeta Linux

### ISSUE THREAD

**Issue by mdtrooper** [planetalinux/planetalinux#271]
Saludos y gracias por el trabajo que hacéis.

Aquí estan los datos:

Nombre autor: Miguel de Dios
Nombre del blog: Tomates Asesinos
URL: http://www.tomatesasesinos.com
URL feeds posts Linux: http://www.tomatesasesinos.com/category/tecnologia/feed/
Descripción del blog: Trata un poco que todo, aunque siempre con un toque a mi amor al software libre y la cultura libre en general, pero quizá la categoría mas "limpia" para el RSS es la de tecnología.

**Comment by julioh** [comment]
Saludos Miguel

Disculpa 2 preguntas, la primera a que instancia de planeta linux quieres participar osea el pais y la otra me puedas dar tu correo para terminar de agregarte.

**Comment by mdtrooper** [comment]
Buenos días.

Si en el estado español.

Y el email es tres.14159@gmail.com .

Saludos.

**Comment by julioh** [comment]
Hola! MIguel

Ya te he agregado a la instancia de Planeta Linux que
solicitaste. ¡Bienvenid@!

Te pedimos que esperes un par de horas para que aparezcas
en el sitio.

También, quisiéramos recordarte que Planeta Linux ha crecido
por gente como tú, por la comunidad usuaria de Linux y
software libre en Latinoamérica que quiere ser parte de este
proyecto. Por ello es que le solicitamos a los nuevos integrantes
que por favor escriban un post en su blog invitando a sus
lectores a leer o unirse a Planeta Linux. Es sólo así como,
de boca en boca, nos hemos dado a conocer y hemos ido
creciendo.

No dudes en contactar nos por cualquier eventualidad.

Bienvenido
