### ISSUE TITLE
Corregir post Viernes 14 de julio de 2017

### ISSUE THREAD

**Issue by DECARTON** [planetalinux/planetalinux#272]
Hola,

en la sección española de planeta linux:   http://planetalinux.org/es/

El primer post: "Cómo buscar stickers para Telegram" tiene fecha incorrecta de julio de 2017 por lo que siempre aparece primero dificultando la letura de los nuevos articulos y perjudicandolos.

He intendado ponerme en contacto con el autor pero no contesta, Espero que puedan solucionarlo por el bien de la comunidad ya que es muy molesto.

Muchas gracias

**Comment by damog** [comment]
Se corrigió mágicamente.
