### ISSUE TITLE
Incluir mi blog al planeta

### ISSUE THREAD

**Issue by BrunoEV** [planetalinux/planetalinux#273]
Estimados administradores de Planeta Linux, me gustaría agregar mi blog (The Linux Alchemist) al planeta de España. Mis datos son los siguiente:

```
Título: The Linux Alchemist
Nombre: Bruno E.V
Email: bruno (dot) exposito (at) openmailbox (dot) com
URL: https://thelinuxalchemist.wordpress.com
Feed: https://thelinuxalchemist.wordpress.com/feed
País: España
```

**Comment by julioh** [comment]
Hola! Bruno

Ya te he agregado a la instancia de Planeta Linux que
solicitaste. ¡Bienvenid@!

Te pedimos que esperes un par de horas para que aparezcas
en el sitio.

También, quisiéramos recordarte que Planeta Linux ha crecido
por gente como tú, por la comunidad usuaria de Linux y
software libre en Latinoamérica que quiere ser parte de este
proyecto. Por ello es que le solicitamos a los nuevos integrantes
que por favor escriban un post en su blog invitando a sus
lectores a leer o unirse a Planeta Linux. Es sólo así como,
de boca en boca, nos hemos dado a conocer y hemos ido
creciendo.

No dudes en contactar nos por cualquier eventualidad.

Bienvenido
