### ISSUE TITLE
Modificar URL de feed en PlanetaLinux

### ISSUE THREAD

**Issue by AdrianArroyoCalle** [planetalinux/planetalinux#280]
Hola, recientemente he cambiado la dirección de mi blog y para que PlanetaLinux siga recibiendo noticias de mi blog es necesario cambiar la URL del feed.

Nombre: Adrián Arroyo
Blog antiguo: http://adrianarroyocalle.github.io/blog/
Nueva dirección del blog: https://blog.adrianistan.eu
Nueva dirección del feed: http://blog.adrianistan.eu/category/programacion/feed

**Comment by vicm3** [comment]
5d19a2f  se realiza el cambio.

**Comment by AdrianArroyoCalle** [comment]
Gracias!
