### ISSUE TITLE
#Guatemala Invitación lanzamiento Endless OS

### ISSUE THREAD

**Issue by erickesteban** [planetalinux/planetalinux#281]
Queremos invitarlos a la presentación del Sistema Operativo Endless. La presentación ser hará en la Ciudad de Guatemala el día martes 5 de Julio a las 18:30 horas (Guatemala). 
Pueden seguir la transmisión en vivo. Tenemos 2 cupos para dicho evento en donde se hará entrega de una copia gratuita, además se rifará una computadora Endless.
Me podrían proporcionar un correo para enviar la invitación por favor?

**Comment by damog** [comment]
Gracias, estuvo muy bueno el evento.
