### ISSUE TITLE
Modificar link de blog

### ISSUE THREAD

**Issue by dragonxtek** [planetalinux/planetalinux#282]
Administradores podrían corregir el link a mi blog?

Nombre: Nicolás Boettcher
Email: nicolas.boettcher@mail.udp.cl
URL: http://installfights.blogspot.cl/
País: Chile

**Comment by vicm3** [comment]
Se corrige la URL con el commit da5eb29

**Comment by dragonxtek** [comment]
quedó mal linkeado. Aparece como link la siguiente url: http://planetalinux.org/cl/
