### ISSUE TITLE
Actualizar Ubuntizando.com como multiautor

### ISSUE THREAD

**Issue by mishagen** [planetalinux/planetalinux#284]
Hola. ¿Es posible actualizar Ubuntizando.com como sitio multiautor? ;)

Gracias 

Miguel Parada
Ubuntizando.com

**Comment by damog** [comment]
¿En qué sentido?

**Comment by mishagen** [comment]
Hola damong,

Me refiero a que desde hace algún tiempo somos lo que podriamos llamar una Comunidad de varios autores en el sitio ubuntizando.com y me gustaría normalizar eso. Quiero decir, cuando se publica contenido en Planetalinux solo aparece mi nombre como autor y muchas entradas son de otros autores, no es justo llevarme el "merito" :)
