### ISSUE TITLE
Problema con mi sitio

### ISSUE THREAD

**Issue by Skatox** [planetalinux/planetalinux#287]
Tengo problemas con sitio, es skatox.com y este debería ser el feed pero no veo que sincronice en vuestro sitio https://skatox.com/blog/category/planetas-linux/feed/atom/ @julioh

**Comment by vicm3** [comment]
Encontré el problema,al pedir el feed recibe uno:
curl -I http://skatox.com/blog/category/planetas-linux/feed/atom/
HTTP/1.1 301 Moved Permanently
[...]
Last-Modified: Mon, 06 Mar 2017 12:40:54 GMT
Location: https://skatox.com/blog/category/planetas-linux/feed/atom/

Al pedir el https
 openssl s_client -showcerts -connect skatox.com:443
CONNECTED(00000003)
140208877360784:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:757:

Entonces lo que estamos obteniendo al pedir el feed normal es vacío.

Te pido que revises, me supongo que en alguna parte de optimización ya sea en cloudflare, w3 o el propio wp, tienes activado que las peticiones sean preferentemente por https, pero no ofreces un certificado válido y por lo menos con la URL que tenemos http, recibo una respuesta vacía a menos que pida la cabecera.

**Comment by Skatox** [comment]
Vale, entiendo. Entonces puedes cambiar el feed a http://feeds.feedburner.com/skatox ?

**Comment by vicm3** [comment]
@Skatox ¿el de feedburner se puede proveer por categorías?

**Comment by Skatox** [comment]
Ya ese feed es la categoría de planeta linux. Mi original con todo es otro.

**Comment by vicm3** [comment]
Añadí el de feedburner y sigue sin actualizar, también por ahí veo unos archivos viejos de configuración (que no se si afecte, que hay yml y yaml) he corrido un par de veces build ve, build www y build flush y no actualiza el feed de skatox @damog a ver si puedes darle un vistazo porque no puedo encontrar la razón.
