### ISSUE TITLE
Update Profile

### ISSUE THREAD

**Issue by k4ch0** [planetalinux/planetalinux#293]
Hi team, 

I've updated my feed url and notice that my profile is not complete, please update my profile (luis_alberto_cacho.yml) with the following information:

email: luiscachog@gmail.com
name: Luis Cacho
twitter: k4ch0
url: http://feeds.feedburner.com/luiscachog

Also, I can provide a png file for my face.

Thanks in advance

**Comment by julioh** [comment]
Ya se realizo.
