### ISSUE TITLE
Reclutamiento

### ISSUE THREAD

**Issue by AlbertoPo** [planetalinux/planetalinux#295]
Hola, tengo oportunidades de Administradores de Linux para una compania americana. Me gustaria publicar los requerimientos en su blog y tambien si me pudieran ayudar que grupos conocen que pueda publicar las vacantes.

Gracias

**Comment by julioh** [comment]
Saludos, Aprecio tu interés, pero no es el fin del proyecto de lo que hacemos en PlanetaLinux.
Te invito a leer que somos.

http://planetalinux.org/faq.html

Puedes ubicar a personas en redes especializadas como linkedin y otras que sobran en la red.
