### ISSUE TITLE
Agregar blog

### ISSUE THREAD

**Issue by merovingio** [planetalinux/planetalinux#296]
Nombre: Damián Digital
Email: damianfossi@gmail.com
URL: https://damian.fossi.es
Feed: https://damian.fossi.es/feed/
País: España

Un saludo.

**Comment by lblack2013** [comment]
Nombre: El Blog de Ly0n
Email: lionblackoverrayd@gmail.com
URL: http://blog.consultoresaplicativos.com
Feed: http://blog.consultoresaplicativos.com/feed/
Pais: El Salvador

Saludos.

**Comment by julioh** [comment]
No
