### ISSUE TITLE
Cambio de dirección de un blog

### ISSUE THREAD

**Issue by gasparfm** [planetalinux/planetalinux#297]
Hola, quisiera notificar el cambio de dirección de mi blog, Poesía Binaria

Antigua dirección: http://totaki.com/poesiabinaria
Nueva dirección: https://poesiabinaria.net/
Mi nombre: Gaspar Fernández

Aunque tengo redirecciones 301 en la antigua dirección, creo que el sistema no ha hecho la redirección y no ha cogido los nuevos contenidos.

Muchas gracias.

**Comment by julioh** [comment]
Saludos Gaspar

Necesito dos cosa
1- tu correo, y twitter si tienes.
2- Necesito un feed en que solo hable linux, para no publicar post que no sean agregados ellos.
por favor crea un feed, pasa 2 post para alla y me pasas el feed para chequearlo, y cambiar la url, para que aparezcas en España

Sin mas

**Comment by julioh** [comment]
Agregado
